### ISSUE TITLE
Como programadora, necesito conocer más detalles de cada inmueble para poder establecer una estructura de datos correcta.

### ISSUE THREAD

**Issue by agr8** [ismaelmontesinos/InmuVenta#18]
Como programadora, dada la HU-1 (#6 ), considero que cada inmueble debe tener un **identificador**, una **localización**, un **precio** y una **descripción** que contenga el número de habitaciones, número de plantas y fecha de la última reforma. Todos los datos anteriores los he obtenido de la descripción de [este Milestone](https://github.com/ismaelmontesinos/PracticaIV/milestone/1).
 Necesito conocer a qué te refieres concretamente con localización ya que pueden existir muchas interpretaciones. Podría referirse al barrio, o bien a la calle, el número del edificio y el piso o la planta, o bien únicamente al código postal...
Por otro lado, me gustaría aclarar si el contenido de la descripción del inmueble es correcta o añadirías o eliminarías alguna característica.

**Comment by ismaelmontesinos** [comment]
La localización se va a definir con los parámetros **código postal**(obligatorio), **tipo de vía**(obligatorio), **nombre de vía**(obligatorio), **número de bloque**(opcional), **número de puerta**(opcional), **planta**(opcional), **puerta**(opcional). Véase tipo de vía como "calle, avenida, carril..."; y toda la parte obligatoria u opcional será por parte del usuario. Esto es, el usuario **DEBE** rellenar los parámetros obligatorios y puede o no rellenar los opcionales, pero la opción debe estar ahí.

La descripción del inmueble será una  descripción por parte del vendedor en la que pueda exponer detalles de su inmueble a placer.

Los parámetros finales de un inmueble deben ser **identificador**, **localización** previamente descrita, **precio**, **descripción**, **número de dormitorios**, **número de cuartos de baño** , **número de planta**, **fecha de la última reforma**, **métros cuadrados totales**, **tenencia o no de garaje**.
